export enum characterActionTypes {
  ADD_CHARACTER = 'ADD_CHARACTER',
  SET_CHARACTER_PROPERTY = 'SET_CHARACTER_PROPERTY',
  SET_CHARACTER_ATTRIBUTE = 'SET_CHARACTER_ATTRIBUTE',
  SET_CHARACTER_SKILL = 'SET_CHARACTER_SKILL',
  SET_CHARACTER_ABILITY = 'SET_CHARACTER_ABILITY',
}